name: empty_widget
description: Custom_Empty widget is flutter custom widget which is designed to notify user about some event.
version: 0.0.5

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/emptyImage.png
    - assets/images/im_emptyIcon_1.png
    - assets/images/im_emptyIcon_2.png
    - assets/images/im_emptyIcon_3.png
